# Use container-based infrastructure for quicker build start-up
sudo: false
language: minimal
env:
  # Path to 'hadolint' binary
  HADOLINT: "${HOME}/hadolint"
install:
  # Download hadolint binary and set it as executable
  - curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-$(uname -s)-$(uname -m)"
  - chmod 700 ${HADOLINT}
script:
  - ${HADOLINT} --ignore DL3016 --ignore DL3003 --ignore DL3008 Dockerfile
  - docker build . -t varnav/lamp
  - docker run --rm -d --name docker-lamp-test varnav/lamp
  - sleep 10
  - docker logs docker-lamp-test | head -n 20
  - docker stop docker-lamp-test